# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.0.8
_src_path: gh:algorandfoundation/algokit-react-frontend-template
author_email: dipanshuhappy@gmail.com
author_name: dipanshuhappy
cloud_provider: vercel
preset_name: production
project_name: allo-algo-web-app-frontend

